[package]
name = "swrt"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.24"
fastrand = "1.9.0"
image = "0.24.6"
glam = "0.24.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
